name: alerthub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2
  auto_route: ^9.2.0
  cached_network_image: ^3.2.1
  cloud_firestore: ^5.4.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.2
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_animate: ^4.1.0
  geolocator: ^12.0.0
  intl: ^0.19.0
  lottie: ^3.1.2
  get: ^4.6.5
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  flutter_svg: ^2.0.2
  focus_detector: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  country_picker: ^2.0.26
  location: ^6.0.2
  google_maps_flutter: ^2.9.0

 
dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  adaptive_icon_background: "#FFFFFF"


flutter:
  uses-material-design: true
 

  assets:
    - assets/logo/
    - assets/images/
    - assets/dump/
    - assets/lottie/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Italic.otf
          style: italic